ALTER TABLE users ADD COLUMN coins INTEGER NOT NULL DEFAULT 100;

ALTER TABLE pvp_rooms
    ADD COLUMN stake_coins INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN language VARCHAR(30) NOT NULL DEFAULT 'JAVA',
    ADD COLUMN public_match BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN winner_id BIGINT REFERENCES users(id);

ALTER TABLE pvp_rooms
    ADD CONSTRAINT chk_pvp_room_stake CHECK (stake_coins BETWEEN 1 AND 1000);

ALTER TABLE pvp_room_players
    ADD COLUMN stake_paid BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN solved_at TIMESTAMP(6);
